core/urls.py
from django.urls import path
from . import views


app_name = 'core'


urlpatterns = [
    path('', views.Home.as_view(), name='home'),
]

post/urls.py
from django.urls import path, include
from . import views 
from .import api_views


app_name = 'post'



api_urls = [
    path('posts/', api_views.PostListView.as_view()),
    path('posts/create/', api_views.PostCreateView.as_view()),
    path('posts/update/int:pk>/', api_views.PostUpdateView.as_view()),
    path('posts/delete/<int:pk>/', api_views.PostDeleteView.as_view()),
]





urlpatterns = [
    path('index/', views.PostList.as_view(), name='index'),
    path('post_delete/<int:p_id>/', views.PostDelete.as_view(), name='post_delete'),
    path('post_download/<str:key>/', views.PostDownload.as_view(), name='post_download'),
    path('api/', include(api_urls)),
]

social/urls.py
from django.contrib import admin
from django.forms import forms
from django.urls import path, include
from rest_framework_simplejwt import views as jwt_views
from rest_framework.authtoken.views import obtain_auth_token
from users.api_views import RegisterApiView
from rest_framework_simplejwt.views import TokenObtainPairView, TokenRefreshView
from users import api_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/users/', include('users.urls', namespace='users')),
    path('auth/refresh-token',TokenRefreshView.as_view(), name='refreshtoken'),
    path('', include('core.urls', namespace='core')),
    path('post/', include('post.urls', namespace='post')),
    path('comment/', include('comment.urls', namespace='comment')),


]

users/urls.py
from django.conf.urls import url
from django.urls import path, include
from . import views
from .api_views  import RegisterApiView, LoginApiView



app_name = 'users'


api_urls = [
    url(r'register/$', RegisterApiView.as_view()),
    url(r'login/$', LoginApiView.as_view())
]







urlpatterns = [
    path('register/', views.UserRegister.as_view(), name='register'),
    path('login/', views.UserLogin.as_view(), name='login'),
    path('logout/', views.UserLogout.as_view(), name='logout'),
     path('api/', include(api_urls)),
    
    
]

templates/inc/messages.html
{% if messages %}
    {% for message in messages %}
        <p class='alert alert-{{ message.tags }}'>{{ message }}</p>
    {% endfor %}
{% endif %}

templates/inc/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="navbar-nav">
        <a href="{% url 'core:home' %}" class="nav-link active">Home</a>
        {% if request.user.is_authenticated %}
        {% comment %} <a  class="nav-link active" href="{% url 'accounts:dashboard' request.user.username %}">Dashboard</a> {% endcomment %}
        <a  class="nav-link active" href="{% url 'post:index'  %}">My Post</a>
        {% comment %} <a  class="nav-link active" href="{% url 'post:post_detail' request.user.username %}">Post Detail</a> {% endcomment %}
        <a  class="nav-link active" href="{% url 'users:logout' %}">Logout</a>
        {% else %}
        <a  class="nav-link active" href="{% url 'users:register' %}">Register</a>
        <a class="nav-link active" href="{% url 'users:login' %}" >Login</a>
        {% endif %}
        

    </div>
</nav>